# Generate files to be used as benchmarks for testing.  The files output by this script should be checked manually to
# ensure that they look okay.  Running test_bother.py will then attempt to replicate these commands and compare the
# output images to the files generated by this script, to ensure that any changes to the code do not unexpectedly
# change the output of the programme.  This script should be run from within the "test" directory, so that the examples
# are saved down to "test/examples".

# Generate TIF files to work with
pipenv run ../bother -ot examples/mallorca.tif -b 39.195468 2.272535 39.998336 3.584351 examples/mallorca.png
pipenv run ../bother -ot examples/ireland.tif -b 51.296094 -11.017116 55.596810 -4.403352 examples/ireland.png
pipenv run ../bother -ot examples/titicaca.tif -b -16.970092 -70.246331 -15.032316 -68.334710 examples/titicaca.png
pipenv run ../bother -ot examples/constance.tif -b 47.321556 8.830936 47.980224 9.860904 examples/constance.png
pipenv run ../bother -ot examples/alps.tif -b 46.408240 9.555657 46.975534 10.378602 examples/alps.png
pipenv run ../bother -ot examples/germany_nw.tif -b 53.373069 7.387423 53.814826 8.234738 examples/germany_nw.png

# Mallorca: Crop image but don't do any other processing (including no reprojection)
pipenv run ../bother -it examples/mallorca.tif --epsg 4326 --crop 1574x787 c -si 2048x1024 examples/mallorca_no_processing_resized.png

# Ireland: Resample, detect lakes, raise low pixels, and (in the second example) flatten the land
pipenv run ../bother -sd 0.5 -l 100 -rl -b 51.296094 -11.017116 55.596810 -4.403352 examples/ireland_resampled_lakes_low_raised.png
pipenv run ../bother -mb 170 -sd 0.5 -l 100 -rl -b 51.296094 -11.017116 55.596810 -4.403352 examples/ireland_resampled_lakes_low_raised_flat.png

# Lake Titicaca: Detect lakes, and:
# - in the second exmaple, reproject to EPSG 3395 (World Mercator);
# - in the third example, "reproject" to EPSG 4326 (WGS84, which shouldn't actually perform any reprojection since the
#   data we get is in WGS84 by default)
pipenv run ../bother -l -b -16.970092 -70.246331 -15.032316 -68.334710 examples/titicaca_lakes.png
pipenv run ../bother --epsg 3395 -l -b -16.970092 -70.246331 -15.032316 -68.334710 examples/titicaca_lakes_3359.png
pipenv run ../bother --epsg 4326 -l -b -16.970092 -70.246331 -15.032316 -68.334710 examples/titicaca_lakes_4326.png

# Germany: Raise undersea pixels and also raise low pixels.
pipenv run ../bother -rl 0 -ru 1 -b 53.373069 7.387423 53.814826 8.234738 examples/germany_nw_undersea_raised.png


